services:
  postgres:
    image: postgres:16-alpine
    container_name: criptoativos-db
    environment:
      POSTGRES_DB: criptoativos
      POSTGRES_USER: criptoativos
      POSTGRES_PASSWORD: criptoativos
    ports:
      - "5432:5432"
    volumes:
      - criptoativos-pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U criptoativos -d criptoativos"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  criptoativos-pgdata:
